apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast
spec:
  replicas: 3
  serviceName: hazelcast
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      containers:
        - name: hazelcast
          image: hazelcast/hazelcast-enterprise:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 5701
          env:
          - name: HZ_LICENSEKEY
            valueFrom:
              secretKeyRef:
                name: hz-license-key
                key: key
---

apiVersion: v1
kind: Service
metadata:
  name: hazelcast
spec:
  type: LoadBalancer
  selector:
    app: hazelcast
  ports:
  - name: hazelcast
    port: 5701